cat daftar_barang_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > daftar_barang_setda.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > daftar_barang_dispu.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > daftar_barang_dishub.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > daftar_barang_dinkes.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > daftar_barang_disdik.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > daftar_barang_kpdad.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > daftar_barang_snt.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > daftar_barang_bpmpd.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > daftar_barang_bppakb.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > daftar_barang_dukcatpil.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > daftar_barang_pertanian.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > daftar_barang_bppkp.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > daftar_barang_perindagkop.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > daftar_barang_kp2tpm.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > daftar_barang_dppkad.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > daftar_barang_inspektorat.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > daftar_barang_bappeda.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > daftar_barang_blhk.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > daftar_barang_disporaparbud.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > daftar_barang_kesbangpol.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > daftar_barang_satpolpp.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > daftar_barang_bkd.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > daftar_barang_paringin.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > daftar_barang_lampihong.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > daftar_barang_batumandi.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > daftar_barang_juai.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > daftar_barang_awayan.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > daftar_barang_halong.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > daftar_barang_paringinselatan.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > daftar_barang_tebingtinggi.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > daftar_barang_bpbd.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > daftar_barang_b40.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > daftar_barang_b41.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > daftar_barang_b42.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > daftar_barang_b43.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > daftar_barang_b44.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > daftar_barang_b45.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > daftar_barang_b46.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > daftar_barang_b47.sql
cat daftar_barang_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > daftar_barang_b48.sql
cat daftar_barang_*.sql > ../gabungan_daftar_barang.sql
