cat kartu_barang2_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > kartu_barang2_setda.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > kartu_barang2_dpupr.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > kartu_barang2_dishub.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > kartu_barang2_dinkes.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > kartu_barang2_disdik.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > kartu_barang2_perpustakaan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > kartu_barang2_sosial.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > kartu_barang2_dpmd.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > kartu_barang2_dpppa.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > kartu_barang2_dukcatpil.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > kartu_barang2_pertanian.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > kartu_barang2_dkp.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > kartu_barang2_dkukmp.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > kartu_barang2_dpmptsp.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > kartu_barang2_bkd.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > kartu_barang2_inspektorat.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > kartu_barang2_bappeda.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > kartu_barang2_dlh.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > kartu_barang2_dko.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > kartu_barang2_kesbangpol.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > kartu_barang2_satpolpp.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > kartu_barang2_bkppd.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > kartu_barang2_paringin.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > kartu_barang2_lampihong.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > kartu_barang2_batumandi.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > kartu_barang2_juai.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > kartu_barang2_awayan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > kartu_barang2_halong.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > kartu_barang2_paringinselatan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > kartu_barang2_tebingtinggi.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > kartu_barang2_bpbd.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > kartu_barang2_dpkp.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > kartu_barang2_disnakertrans.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > kartu_barang2_dppkb.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > kartu_barang2_kominfo.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > kartu_barang2_kearsipan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > kartu_barang2_perikanan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > kartu_barang2_pariwisata.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > kartu_barang2_perdagangan.sql
cat kartu_barang2_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > kartu_barang2_bppd.sql
cat kartu_barang2_*.sql > ../gabungan_kartu_barang2.sql
