cat buku_pengeluaran_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > buku_pengeluaran_setda.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > buku_pengeluaran_dpupr.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > buku_pengeluaran_dishub.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > buku_pengeluaran_dinkes.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > buku_pengeluaran_disdik.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > buku_pengeluaran_perpustakaan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > buku_pengeluaran_sosial.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > buku_pengeluaran_dpmd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > buku_pengeluaran_dpppa.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > buku_pengeluaran_dukcatpil.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > buku_pengeluaran_pertanian.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > buku_pengeluaran_dkp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > buku_pengeluaran_dkukmp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > buku_pengeluaran_dpmptsp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > buku_pengeluaran_bkd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > buku_pengeluaran_inspektorat.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > buku_pengeluaran_bappeda.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > buku_pengeluaran_dlh.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > buku_pengeluaran_dko.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > buku_pengeluaran_kesbangpol.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > buku_pengeluaran_satpolpp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > buku_pengeluaran_bkppd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > buku_pengeluaran_paringin.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > buku_pengeluaran_lampihong.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > buku_pengeluaran_batumandi.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > buku_pengeluaran_juai.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > buku_pengeluaran_awayan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > buku_pengeluaran_halong.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > buku_pengeluaran_paringinselatan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > buku_pengeluaran_tebingtinggi.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > buku_pengeluaran_bpbd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > buku_pengeluaran_dpkp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > buku_pengeluaran_disnakertrans.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > buku_pengeluaran_dppkb.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > buku_pengeluaran_kominfo.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > buku_pengeluaran_kearsipan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > buku_pengeluaran_perikanan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > buku_pengeluaran_pariwisata.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > buku_pengeluaran_perdagangan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > buku_pengeluaran_bppd.sql
cat buku_pengeluaran_*.sql > ../gabungan_buku_pengeluaran.sql
