cat buku_pengeluaran_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > buku_pengeluaran_setda.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > buku_pengeluaran_dispu.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > buku_pengeluaran_dishub.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > buku_pengeluaran_dinkes.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > buku_pengeluaran_disdik.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > buku_pengeluaran_kpdad.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > buku_pengeluaran_snt.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > buku_pengeluaran_bpmpd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > buku_pengeluaran_bppakb.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > buku_pengeluaran_dukcatpil.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > buku_pengeluaran_pertanian.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > buku_pengeluaran_bppkp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > buku_pengeluaran_perindagkop.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > buku_pengeluaran_kp2tpm.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > buku_pengeluaran_dppkad.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > buku_pengeluaran_inspektorat.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > buku_pengeluaran_bappeda.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > buku_pengeluaran_blhk.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > buku_pengeluaran_disporaparbud.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > buku_pengeluaran_kesbangpol.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > buku_pengeluaran_satpolpp.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > buku_pengeluaran_bkd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > buku_pengeluaran_paringin.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > buku_pengeluaran_lampihong.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > buku_pengeluaran_batumandi.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > buku_pengeluaran_juai.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > buku_pengeluaran_awayan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > buku_pengeluaran_halong.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > buku_pengeluaran_paringinselatan.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > buku_pengeluaran_tebingtinggi.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > buku_pengeluaran_bpbd.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > buku_pengeluaran_b40.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > buku_pengeluaran_b41.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > buku_pengeluaran_b42.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > buku_pengeluaran_b43.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > buku_pengeluaran_b44.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > buku_pengeluaran_b45.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > buku_pengeluaran_b46.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > buku_pengeluaran_b47.sql
cat buku_pengeluaran_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > buku_pengeluaran_b48.sql
cat buku_pengeluaran_*.sql > ../gabungan_buku_pengeluaran.sql
