cat beban_barang4_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > beban_barang4_setda.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > beban_barang4_dpupr.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > beban_barang4_dishub.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > beban_barang4_dinkes.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > beban_barang4_disdik.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > beban_barang4_perpustakaan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > beban_barang4_sosial.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > beban_barang4_dpmd.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > beban_barang4_dpppa.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > beban_barang4_dukcatpil.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > beban_barang4_pertanian.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > beban_barang4_dkp.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > beban_barang4_dkukmp.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > beban_barang4_dpmptsp.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > beban_barang4_bkd.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > beban_barang4_inspektorat.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > beban_barang4_bappeda.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > beban_barang4_dlh.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > beban_barang4_dko.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > beban_barang4_kesbangpol.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > beban_barang4_satpolpp.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > beban_barang4_bkppd.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > beban_barang4_paringin.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > beban_barang4_lampihong.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > beban_barang4_batumandi.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > beban_barang4_juai.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > beban_barang4_awayan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > beban_barang4_halong.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > beban_barang4_paringinselatan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > beban_barang4_tebingtinggi.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > beban_barang4_bpbd.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > beban_barang4_dpkp.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > beban_barang4_disnakertrans.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > beban_barang4_dppkb.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > beban_barang4_kominfo.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > beban_barang4_kearsipan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > beban_barang4_perikanan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > beban_barang4_pariwisata.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > beban_barang4_perdagangan.sql
cat beban_barang4_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > beban_barang4_bppd.sql
cat beban_barang4_*.sql >> ../gabungan_beban_rinci_kabupaten.sql
