cat daftar_pengadaan_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > daftar_pengadaan_setda.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > daftar_pengadaan_dpupr.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > daftar_pengadaan_dishub.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > daftar_pengadaan_dinkes.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > daftar_pengadaan_disdik.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > daftar_pengadaan_perpustakaan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > daftar_pengadaan_sosial.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > daftar_pengadaan_dpmd.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > daftar_pengadaan_dpppa.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > daftar_pengadaan_dukcatpil.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > daftar_pengadaan_pertanian.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > daftar_pengadaan_dkp.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > daftar_pengadaan_dkukmp.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > daftar_pengadaan_dpmptsp.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > daftar_pengadaan_bkd.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > daftar_pengadaan_inspektorat.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > daftar_pengadaan_bappeda.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > daftar_pengadaan_dlh.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > daftar_pengadaan_dko.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > daftar_pengadaan_kesbangpol.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > daftar_pengadaan_satpolpp.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > daftar_pengadaan_bkppd.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > daftar_pengadaan_paringin.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > daftar_pengadaan_lampihong.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > daftar_pengadaan_batumandi.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > daftar_pengadaan_juai.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > daftar_pengadaan_awayan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > daftar_pengadaan_halong.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > daftar_pengadaan_paringinselatan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > daftar_pengadaan_tebingtinggi.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > daftar_pengadaan_bpbd.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > daftar_pengadaan_dpkp.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > daftar_pengadaan_disnakertrans.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > daftar_pengadaan_dppkb.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > daftar_pengadaan_kominfo.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > daftar_pengadaan_kearsipan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > daftar_pengadaan_perikanan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > daftar_pengadaan_pariwisata.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > daftar_pengadaan_perdagangan.sql
cat daftar_pengadaan_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > daftar_pengadaan_bppd.sql
cat daftar_pengadaan_*.sql > ../gabungan_daftar_pengadaan.sql
