cat beban_barang5_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > beban_barang5_setda.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > beban_barang5_dispu.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > beban_barang5_dishub.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > beban_barang5_dinkes.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > beban_barang5_rsud.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > beban_barang5_disdik.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > beban_barang5_kpdad.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > beban_barang5_snt.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > beban_barang5_bpmpd.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > beban_barang5_bppakb.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > beban_barang5_dukcatpil.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > beban_barang5_pertanian.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > beban_barang5_kehutanan.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > beban_barang5_bppkp.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > beban_barang5_perindagkop.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > beban_barang5_distamben.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > beban_barang5_kp2tpm.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > beban_barang5_dppkad.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > beban_barang5_inspektorat.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > beban_barang5_bappeda.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > beban_barang5_blhk.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > beban_barang5_disporaparbud.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > beban_barang5_kesbangpol.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > beban_barang5_satpolpp.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > beban_barang5_bkd.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > beban_barang5_korpri.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > beban_barang5_paringin.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > beban_barang5_paringinkota.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > beban_barang5_paringintimur.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > beban_barang5_lampihong.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > beban_barang5_batumandi.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > beban_barang5_juai.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > beban_barang5_awayan.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > beban_barang5_halong.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > beban_barang5_paringinselatan.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > beban_barang5_batupiring.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > beban_barang5_tebingtinggi.sql
cat beban_barang5_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > beban_barang5_bpbd.sql

cat beban_barang5_*.sql > ../gabungan_beban_rekap_kabupaten.sql
