cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/dispu/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>3/g >  03_dispu/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/dishub/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>4/g >  04_dishub/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/dinkes/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>5/g >  05_dinkes/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/rsud/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>6/g >  06_rsud/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/disdik/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>7/g >  07_disdik/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/kpdad/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>8/g >  08_kpdad/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/snt/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>9/g >  09_snt/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bpmpd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>10/g >  10_bpmpd/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bppakb/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>11/g >  11_bppakb/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/dukcatpil/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>12/g >  12_dukcatpil/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/pertanian/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>13/g >  13_pertanian/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/kehutanan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>14/g >  14_kehutanan/daftar_pengeluaran_skpd.xml
#cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bppkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\15/g >  15_bppkp/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/perindagkop/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>16/g >  16_perindagkop/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/distamben/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>17/g >  17_distamben/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/kp2tpm/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>18/g >  18_kp2tpm/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/dppkad/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>19/g >  19_dppkad/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/inspektorat/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>20/g >  20_inspektorat/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bappeda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>21/g >  21_bappeda/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/blhk/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>22/g >  22_blhk/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/disporaparbud/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>23/g >  23_disporaparbud/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/kesbangpol/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>24/g >  24_kesbangpol/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/satpolpp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>25/g >  25_satpolpp/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bkd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>26/g >  26_bkd/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/korpri/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>27/g >  27_korpri/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/paringin/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>28/g >  28_paringin/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/paringinkota/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>29/g >  29_paringinkota/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/paringintimur/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>30/g >  30_paringintimur/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/lampihong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>31/g >  31_lampihong/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/batumandi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>32/g >  32_batumandi/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/juai/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>33/g >  33_juai/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/awayan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>34/g >  34_awayan/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/halong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>35/g >  35_halong/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/paringinselatan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>36/g >  36_paringinselatan/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/batupiring/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>37/g >  37_batupiring/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/tebingtinggi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>38/g >  38_tebingtinggi/daftar_pengeluaran_skpd.xml
cat 01_setwan/daftar_pengeluaran_skpd.xml | sed -e s/setwan/bpbd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>39/g >  39_bpbd/daftar_pengeluaran_skpd.xml
