cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/dispu/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>3/g >  03_dispu/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/dishub/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>4/g >  04_dishub/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/dinkes/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>5/g >  05_dinkes/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/rsud/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>6/g >  06_rsud/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/disdik/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>7/g >  07_disdik/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/kpdad/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>8/g >  08_kpdad/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/snt/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>9/g >  09_snt/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bpmpd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>10/g >  10_bpmpd/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bppakb/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>11/g >  11_bppakb/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/dukcatpil/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>12/g >  12_dukcatpil/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/pertanian/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>13/g >  13_pertanian/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/kehutanan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>14/g >  14_kehutanan/rekap_kartu_barang_skpd.xml
#cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bppkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\15/g >  15_bppkp/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/perindagkop/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>16/g >  16_perindagkop/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/distamben/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>17/g >  17_distamben/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/kp2tpm/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>18/g >  18_kp2tpm/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/dppkad/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>19/g >  19_dppkad/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/inspektorat/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>20/g >  20_inspektorat/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bappeda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>21/g >  21_bappeda/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/blhk/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>22/g >  22_blhk/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/disporaparbud/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>23/g >  23_disporaparbud/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/kesbangpol/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>24/g >  24_kesbangpol/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/satpolpp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>25/g >  25_satpolpp/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bkd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>26/g >  26_bkd/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/korpri/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>27/g >  27_korpri/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/paringin/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>28/g >  28_paringin/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/paringinkota/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>29/g >  29_paringinkota/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/paringintimur/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>30/g >  30_paringintimur/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/lampihong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>31/g >  31_lampihong/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/batumandi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>32/g >  32_batumandi/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/juai/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>33/g >  33_juai/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/awayan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>34/g >  34_awayan/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/halong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>35/g >  35_halong/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/paringinselatan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>36/g >  36_paringinselatan/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/batupiring/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>37/g >  37_batupiring/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/tebingtinggi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>38/g >  38_tebingtinggi/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/setwan/bpbd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>39/g >  39_bpbd/rekap_kartu_barang_skpd.xml
#cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/barang3_setwan/barang_rekap_kabupaten/g > kabupaten/rekap_kartu_barang_skpd.xml
cat 01_setwan/rekap_kartu_barang_skpd.xml | sed -e s/barang3_setwan/barang_rekap_kabupaten/g > kabupaten_total/rekap_kartu_barang_skpd.xml
