cvs add kabupaten/*.xml
cvs add 01_setwan/*.xml
cvs add 02_setda/*.xml
cvs add 03_dispu/*.xml
cvs add 04_dishub/*.xml
cvs add 05_dinkes/*.xml
cvs add 06_rsud/*.xml
cvs add 07_disdik/*.xml
cvs add 08_kpdad/*.xml
cvs add 09_snt/*.xml
cvs add 10_bpmpd/*.xml
cvs add 11_bppakb/*.xml
cvs add 12_dukcatpil/*.xml
cvs add 13_pertanian/*.xml
cvs add 14_kehutanan/*.xml
cvs add 15_bppkp/*.xml
cvs add 16_perindagkop/*.xml
cvs add 17_distamben/*.xml
cvs add 18_kp2tpm/*.xml
cvs add 19_dppkad/*.xml
cvs add 20_inspektorat/*.xml
cvs add 21_bappeda/*.xml
cvs add 22_blhk/*.xml
cvs add 23_disporaparbud/*.xml
cvs add 24_kesbangpol/*.xml
cvs add 25_satpolpp/*.xml
cvs add 26_bkd/*.xml
cvs add 27_korpri/*.xml
cvs add 28_paringin/*.xml
cvs add 29_paringinkota/*.xml
cvs add 30_paringintimur/*.xml
cvs add 31_lampihong/*.xml
cvs add 32_batumandi/*.xml
cvs add 33_juai/*.xml
cvs add 34_awayan/*.xml
cvs add 35_halong/*.xml
cvs add 36_paringinselatan/*.xml
cvs add 37_batupiring/*.xml
cvs add 38_tebingtinggi/*.xml
cvs add 39_bpbd/*.xml
