cat kartu_barang_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > kartu_barang_setda.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > kartu_barang_dispu.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > kartu_barang_dishub.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > kartu_barang_dinkes.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > kartu_barang_rsud.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > kartu_barang_disdik.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > kartu_barang_kpdad.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > kartu_barang_snt.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > kartu_barang_bpmpd.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > kartu_barang_bppakb.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > kartu_barang_dukcatpil.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > kartu_barang_pertanian.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > kartu_barang_kehutanan.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > kartu_barang_bppkp.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > kartu_barang_perindagkop.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > kartu_barang_distamben.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > kartu_barang_kp2tpm.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > kartu_barang_dppkad.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > kartu_barang_inspektorat.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > kartu_barang_bappeda.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > kartu_barang_blhk.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > kartu_barang_disporaparbud.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > kartu_barang_kesbangpol.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > kartu_barang_satpolpp.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > kartu_barang_bkd.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > kartu_barang_korpri.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > kartu_barang_paringin.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > kartu_barang_paringinkota.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > kartu_barang_paringintimur.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > kartu_barang_lampihong.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > kartu_barang_batumandi.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > kartu_barang_juai.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > kartu_barang_awayan.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > kartu_barang_halong.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > kartu_barang_paringinselatan.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > kartu_barang_batupiring.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > kartu_barang_tebingtinggi.sql
cat kartu_barang_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > kartu_barang_bpbd.sql

cat kartu_barang_*.sql > ../gabungan_kartu_barang1.sql
