
cvs add  setwan/*.py
cvs add  setda/*.py
cvs add  dispu/*.py
cvs add  dishub/*.py
cvs add  dinkes/*.py
cvs add  rsud/*.py
cvs add  disdik/*.py
cvs add  kpdad/*.py
cvs add  snt/*.py
cvs add  bpmpd/*.py
cvs add  bppakb/*.py
cvs add  dukcatpil/*.py
cvs add  pertanian/*.py
cvs add  kehutanan/*.py
cvs add  bppkp/*.py
cvs add  perindagkop/*.py
cvs add  distamben/*.py
cvs add  kp2tpm/*.py
cvs add  dppkad/*.py
cvs add  inspektorat/*.py
cvs add  bappeda/*.py
cvs add  blhk/*.py
cvs add  disporaparbud/*.py
cvs add  kesbangpol/*.py
cvs add  satpolpp/*.py
cvs add  bkd/*.py
cvs add  korpri/*.py
cvs add  paringin/*.py
cvs add  paringinkota/*.py
cvs add  paringintimur/*.py
cvs add  lampihong/*.py
cvs add  batumandi/*.py
cvs add  juai/*.py
cvs add  awayan/*.py
cvs add  halong/*.py
cvs add  paringinselatan/*.py
cvs add  batupiring/*.py
cvs add  tebingtinggi/*.py
cvs add  bpbd/*.py
