
cvs add  setwan/migrations
cvs add  setda/migrations
cvs add  dispu/migrations
cvs add  dishub/migrations
cvs add  dinkes/migrations
cvs add  rsud/migrations
cvs add  disdik/migrations
cvs add  kpdad/migrations
cvs add  snt/migrations
cvs add  bpmpd/migrations
cvs add  bppakb/migrations
cvs add  dukcatpil/migrations
cvs add  pertanian/migrations
cvs add  kehutanan/migrations
cvs add  bppkp/migrations
cvs add  perindagkop/migrations
cvs add  distamben/migrations
cvs add  kp2tpm/migrations
cvs add  dppkad/migrations
cvs add  inspektorat/migrations
cvs add  bappeda/migrations
cvs add  blhk/migrations
cvs add  disporaparbud/migrations
cvs add  kesbangpol/migrations
cvs add  satpolpp/migrations
cvs add  bkd/migrations
cvs add  korpri/migrations
cvs add  paringin/migrations
cvs add  paringinkota/migrations
cvs add  paringintimur/migrations
cvs add  lampihong/migrations
cvs add  batumandi/migrations
cvs add  juai/migrations
cvs add  awayan/migrations
cvs add  halong/migrations
cvs add  paringinselatan/migrations
cvs add  batupiring/migrations
cvs add  tebingtinggi/migrations
cvs add  bpbd/migrations
