
cvs add  setwan/migrations/*.py
cvs add  setda/migrations/*.py
cvs add  dispu/migrations/*.py
cvs add  dishub/migrations/*.py
cvs add  dinkes/migrations/*.py
cvs add  rsud/migrations/*.py
cvs add  disdik/migrations/*.py
cvs add  kpdad/migrations/*.py
cvs add  snt/migrations/*.py
cvs add  bpmpd/migrations/*.py
cvs add  bppakb/migrations/*.py
cvs add  dukcatpil/migrations/*.py
cvs add  pertanian/migrations/*.py
cvs add  kehutanan/migrations/*.py
cvs add  bppkp/migrations/*.py
cvs add  perindagkop/migrations/*.py
cvs add  distamben/migrations/*.py
cvs add  kp2tpm/migrations/*.py
cvs add  dppkad/migrations/*.py
cvs add  inspektorat/migrations/*.py
cvs add  bappeda/migrations/*.py
cvs add  blhk/migrations/*.py
cvs add  disporaparbud/migrations/*.py
cvs add  kesbangpol/migrations/*.py
cvs add  satpolpp/migrations/*.py
cvs add  bkd/migrations/*.py
cvs add  korpri/migrations/*.py
cvs add  paringin/migrations/*.py
cvs add  paringinkota/migrations/*.py
cvs add  paringintimur/migrations/*.py
cvs add  lampihong/migrations/*.py
cvs add  batumandi/migrations/*.py
cvs add  juai/migrations/*.py
cvs add  awayan/migrations/*.py
cvs add  halong/migrations/*.py
cvs add  paringinselatan/migrations/*.py
cvs add  batupiring/migrations/*.py
cvs add  tebingtinggi/migrations/*.py
cvs add  bpbd/migrations/*.py
