cat buku_penerimaan_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > buku_penerimaan_setda.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > buku_penerimaan_dispu.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > buku_penerimaan_dishub.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > buku_penerimaan_dinkes.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > buku_penerimaan_rsud.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > buku_penerimaan_disdik.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > buku_penerimaan_kpdad.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > buku_penerimaan_snt.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > buku_penerimaan_bpmpd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > buku_penerimaan_bppakb.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > buku_penerimaan_dukcatpil.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > buku_penerimaan_pertanian.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > buku_penerimaan_kehutanan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > buku_penerimaan_bppkp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > buku_penerimaan_perindagkop.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > buku_penerimaan_distamben.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > buku_penerimaan_kp2tpm.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > buku_penerimaan_dppkad.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > buku_penerimaan_inspektorat.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > buku_penerimaan_bappeda.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > buku_penerimaan_blhk.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > buku_penerimaan_disporaparbud.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > buku_penerimaan_kesbangpol.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > buku_penerimaan_satpolpp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > buku_penerimaan_bkd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > buku_penerimaan_korpri.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > buku_penerimaan_paringin.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > buku_penerimaan_paringinkota.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > buku_penerimaan_paringintimur.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > buku_penerimaan_lampihong.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > buku_penerimaan_batumandi.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > buku_penerimaan_juai.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > buku_penerimaan_awayan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > buku_penerimaan_halong.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > buku_penerimaan_paringinselatan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > buku_penerimaan_batupiring.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > buku_penerimaan_tebingtinggi.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > buku_penerimaan_bpbd.sql

cat buku_penerimaan_*.sql > ../gabungan_buku_penerimaan.sql
