cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > daftar_pengeluaran_setda.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > daftar_pengeluaran_dispu.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > daftar_pengeluaran_dishub.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > daftar_pengeluaran_dinkes.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > daftar_pengeluaran_rsud.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > daftar_pengeluaran_disdik.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > daftar_pengeluaran_kpdad.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > daftar_pengeluaran_snt.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > daftar_pengeluaran_bpmpd.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > daftar_pengeluaran_bppakb.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > daftar_pengeluaran_dukcatpil.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > daftar_pengeluaran_pertanian.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > daftar_pengeluaran_kehutanan.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > daftar_pengeluaran_bppkp.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > daftar_pengeluaran_perindagkop.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > daftar_pengeluaran_distamben.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > daftar_pengeluaran_kp2tpm.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > daftar_pengeluaran_dppkad.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > daftar_pengeluaran_inspektorat.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > daftar_pengeluaran_bappeda.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > daftar_pengeluaran_blhk.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > daftar_pengeluaran_disporaparbud.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > daftar_pengeluaran_kesbangpol.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > daftar_pengeluaran_satpolpp.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > daftar_pengeluaran_bkd.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > daftar_pengeluaran_korpri.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > daftar_pengeluaran_paringin.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > daftar_pengeluaran_paringinkota.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > daftar_pengeluaran_paringintimur.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > daftar_pengeluaran_lampihong.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > daftar_pengeluaran_batumandi.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > daftar_pengeluaran_juai.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > daftar_pengeluaran_awayan.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > daftar_pengeluaran_halong.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > daftar_pengeluaran_paringinselatan.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > daftar_pengeluaran_batupiring.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > daftar_pengeluaran_tebingtinggi.sql
cat daftar_pengeluaran_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > daftar_pengeluaran_bpbd.sql

cat daftar_pengeluaran_*.sql > ../gabungan_daftar_pengeluaran.sql
