# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsalUsul',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('asal_usul', models.CharField(db_column=b'asal_usul', max_length=200, verbose_name=b'Asal Usul')),
            ],
            options={
                'db_table': 'asal_usul',
                'verbose_name': 'Asal Usul',
                'verbose_name_plural': 'Asal Usul',
            },
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(db_column=b'nama_barang', max_length=200, unique=True, verbose_name=b'Nama Barang')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'barang',
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_jenis_barang', models.CharField(db_column=b'kode_jenis_barang', max_length=40, unique=True, verbose_name=b'Kode Jenis Barang')),
                ('jenis_barang', models.CharField(db_column=b'jenis_barang', max_length=200, unique=True, verbose_name=b'Jenis Barang')),
            ],
            options={
                'db_table': 'jenis_barang',
                'verbose_name': 'Jenis Barang',
                'verbose_name_plural': 'Jenis Barang',
            },
        ),
        migrations.CreateModel(
            name='JenisKeluar',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('jenis_keluar', models.CharField(db_column=b'jenis_keluar', max_length=200, verbose_name=b'Jenis Keluar')),
            ],
            options={
                'db_table': 'jenis_keluar',
                'verbose_name': 'Jenis Keluar',
                'verbose_name_plural': 'Jenis Keluar',
            },
        ),
        migrations.CreateModel(
            name='JenisTransaksi',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('jenis_transaksi', models.CharField(db_column=b'jenis_transaksi', max_length=40, unique=True, verbose_name=b'Jenis Transaksi')),
            ],
            options={
                'db_table': 'jenis_transaksi',
                'verbose_name': 'Jenis Transaksi',
                'verbose_name_plural': 'Jenis Transaksi',
            },
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_kabupaten', models.CharField(db_column=b'kode_kabupaten', max_length=20, verbose_name=b'Kode Kabupaten')),
                ('nama_kabupaten', models.CharField(db_column=b'nama_kabupaten', max_length=200, verbose_name=b'Nama Kabupaten')),
            ],
            options={
                'db_table': 'kabupaten',
                'verbose_name': 'Kabupaten',
                'verbose_name_plural': 'Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='LokasiBidang',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_lokasi_bidang', models.CharField(db_column=b'kode_lokasi_bidang', max_length=20, verbose_name=b'Kode Lokasi Bidang')),
                ('nama_lokasi_bidang', models.CharField(db_column=b'nama_lokasi_bidang', max_length=200, verbose_name=b'Nama Lokasi Bidang')),
                ('id_kabupaten', models.ForeignKey(db_column=b'id_kabupaten', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Kabupaten', verbose_name=b'Kabupaten')),
            ],
            options={
                'db_table': 'lokasi_bidang',
                'verbose_name': 'Lokasi Bidang',
                'verbose_name_plural': 'Lokasi Bidang',
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(db_column=b'nama_pegawai', max_length=200, verbose_name=b'Nama Pegawai')),
                ('nip', models.CharField(db_column=b'nip', max_length=60, verbose_name=b'NIP')),
            ],
            options={
                'db_table': 'pegawai',
                'verbose_name': 'Pegawai',
                'verbose_name_plural': 'Pegawai',
            },
        ),
        migrations.CreateModel(
            name='Persediaan',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('tanggal_kadaluarsa', models.DateField(blank=True, db_column=b'tanggal_kadaluarsa', null=True, verbose_name=b'Tanggal Kadaluarsa')),
                ('jumlah', models.IntegerField(db_column=b'jumlah', default=0, verbose_name=b'Jumlah')),
                ('harga', models.DecimalField(db_column=b'harga', decimal_places=0, default=0, max_digits=15, verbose_name=b'Harga')),
                ('id_barang', models.ForeignKey(db_column=b'id_barang', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Barang', verbose_name=b'Barang')),
            ],
            options={
                'db_table': 'persediaan',
                'verbose_name': 'Persediaan',
                'verbose_name_plural': 'Persediaan',
            },
        ),
        migrations.CreateModel(
            name='PihakKetiga',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('nama_pihak_ketiga', models.CharField(db_column=b'nama_pihak_ketiga', max_length=200, verbose_name=b'Nama Pihak Ketiga')),
            ],
            options={
                'db_table': 'pihak_ketiga',
                'verbose_name': 'Pihak Ketiga',
                'verbose_name_plural': 'Pihak Ketiga',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_provinsi', models.CharField(db_column=b'kode_provinsi', max_length=20, verbose_name=b'Kode Provinsi')),
                ('nama_provinsi', models.CharField(db_column=b'nama_provinsi', max_length=200, verbose_name=b'Nama Provinsi')),
            ],
            options={
                'db_table': 'provinsi',
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('satuan', models.CharField(db_column=b'satuan', max_length=60, unique=True, verbose_name=b'Satuan')),
            ],
            options={
                'db_table': 'satuan',
                'verbose_name': 'Satuan',
                'verbose_name_plural': 'Satuan',
            },
        ),
        migrations.CreateModel(
            name='SKPD',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_skpd', models.CharField(db_column=b'kode_skpd', max_length=20, verbose_name=b'Kode SKPD')),
                ('nama_skpd', models.CharField(db_column=b'nama_skpd', max_length=200, verbose_name=b'Nama SKPD')),
                ('id_lokasi_bidang', models.ForeignKey(db_column=b'id_lokasi_bidang', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.LokasiBidang', verbose_name=b'Lokasi Bidang')),
            ],
            options={
                'db_table': 'skpd',
                'verbose_name': 'SKPD',
                'verbose_name_plural': 'SKPD',
            },
        ),
        migrations.CreateModel(
            name='StatusPegawai',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('status_pegawai', models.CharField(db_column=b'status_pegawai', max_length=40, unique=True, verbose_name=b'Status Pegawai')),
            ],
            options={
                'db_table': 'status_pegawai',
                'verbose_name': 'Status Pegawai',
                'verbose_name_plural': 'Status Pegawai',
            },
        ),
        migrations.CreateModel(
            name='SUBSKPD',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('kode_sub_skpd', models.CharField(db_column=b'kode_sub_skpd', max_length=20, verbose_name=b'Kode SUB SKPD')),
                ('nama_sub_skpd', models.CharField(db_column=b'nama_sub_skpd', max_length=200, verbose_name=b'Nama SUB SKPD')),
                ('id_skpd', models.ForeignKey(db_column=b'id_skpd', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.SKPD', verbose_name=b'SKPD')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'sub_skpd',
                'verbose_name': 'SUB SKPD',
                'verbose_name_plural': 'SUB SKPD',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False, verbose_name=b'Kode Transaksi')),
                ('tanggal', models.DateField(db_column=b'tanggal', verbose_name=b'Tanggal')),
                ('keterangan', models.CharField(db_column=b'keterangan', max_length=200, verbose_name=b'Keterangan')),
            ],
            options={
                'db_table': 'transaksi',
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='Keluar',
            fields=[
                ('id', models.OneToOneField(db_column=b'id_transaksi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kabupaten.Transaksi')),
                ('id_jenis_keluar', models.ForeignKey(db_column=b'id_jenis_keluar', default=1, on_delete=django.db.models.deletion.CASCADE, to='kabupaten.JenisKeluar', verbose_name=b'Jenis Keluar')),
            ],
            options={
                'db_table': 'keluar',
                'verbose_name': 'Keluar',
                'verbose_name_plural': 'Keluar',
            },
        ),
        migrations.CreateModel(
            name='Masuk',
            fields=[
                ('id', models.OneToOneField(db_column=b'id_transaksi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kabupaten.Transaksi')),
                ('id_asal_usul', models.ForeignKey(db_column=b'id_asal_usul', default=1, on_delete=django.db.models.deletion.CASCADE, to='kabupaten.AsalUsul', verbose_name=b'Asal Usul')),
            ],
            options={
                'db_table': 'masuk',
                'verbose_name': 'Masuk',
                'verbose_name_plural': 'Masuk',
            },
        ),
        migrations.AddField(
            model_name='transaksi',
            name='id_jenis_transaksi',
            field=models.ForeignKey(db_column=b'id_jenis_transaksi', null=True, on_delete=django.db.models.deletion.CASCADE, to='kabupaten.JenisTransaksi', verbose_name=b'Jenis Transaksi'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='id_sub_skpd',
            field=models.ForeignKey(db_column=b'id_sub_skpd', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.SUBSKPD', verbose_name=b'SUB SKPD'),
        ),
        migrations.AddField(
            model_name='pihakketiga',
            name='id_skpd',
            field=models.ForeignKey(db_column=b'id_skpd', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.SKPD', verbose_name=b'SKPD'),
        ),
        migrations.AddField(
            model_name='persediaan',
            name='id_transaksi',
            field=models.ForeignKey(db_column=b'id_transaksi', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Transaksi', verbose_name=b'Transaksi'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_skpd',
            field=models.ForeignKey(db_column=b'id_skpd', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.SKPD', verbose_name=b'SKPD'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='id_status_pegawai',
            field=models.ForeignKey(db_column=b'id_status_pegawai', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.StatusPegawai', verbose_name=b'Status Pegawai'),
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='id_provinsi',
            field=models.ForeignKey(db_column=b'id_provinsi', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Provinsi', verbose_name=b'Provinsi'),
        ),
        migrations.AddField(
            model_name='barang',
            name='id_jenis_barang',
            field=models.ForeignKey(db_column=b'id_jenis_barang', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.JenisBarang', verbose_name=b'Jenis Barang'),
        ),
        migrations.AddField(
            model_name='barang',
            name='id_satuan',
            field=models.ForeignKey(db_column=b'id_satuan', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Satuan', verbose_name=b'Satuan'),
        ),
        migrations.CreateModel(
            name='PegawaiSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Pegawai Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Pegawai Setwan',
                'indexes': [],
            },
            bases=('kabupaten.pegawai',),
        ),
        migrations.CreateModel(
            name='PersediaanKeluar',
            fields=[
            ],
            options={
                'verbose_name': 'Persediaan Keluar',
                'proxy': True,
                'verbose_name_plural': 'Persediaan Keluar',
                'indexes': [],
            },
            bases=('kabupaten.persediaan',),
        ),
        migrations.CreateModel(
            name='PersediaanKeluarSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Persediaan Keluar Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Persediaan Keluar Setwan',
                'indexes': [],
            },
            bases=('kabupaten.persediaan',),
        ),
        migrations.CreateModel(
            name='PersediaanMasuk',
            fields=[
            ],
            options={
                'verbose_name': 'Persediaan Masuk',
                'proxy': True,
                'verbose_name_plural': 'Persediaan Masuk',
                'indexes': [],
            },
            bases=('kabupaten.persediaan',),
        ),
        migrations.CreateModel(
            name='PersediaanMasukSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Persediaan Masuk Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Persediaan Masuk Setwan',
                'indexes': [],
            },
            bases=('kabupaten.persediaan',),
        ),
        migrations.CreateModel(
            name='PihakKetigaSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Pihak Ketiga Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Pihak Ketiga Setwan',
                'indexes': [],
            },
            bases=('kabupaten.pihakketiga',),
        ),
        migrations.CreateModel(
            name='TambahBarang',
            fields=[
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tambah Barang',
                'proxy': True,
                'verbose_name_plural': 'Tambah Barang',
                'indexes': [],
            },
            bases=('kabupaten.barang',),
        ),
        migrations.CreateModel(
            name='TransaksiKeluar',
            fields=[
            ],
            options={
                'verbose_name': 'Transaksi Keluar',
                'proxy': True,
                'verbose_name_plural': 'Transaksi Keluar',
                'indexes': [],
            },
            bases=('kabupaten.transaksi',),
        ),
        migrations.CreateModel(
            name='TransaksiKeluarSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Transaksi Keluar Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Transaksi Keluar Setwan',
                'indexes': [],
            },
            bases=('kabupaten.transaksi',),
        ),
        migrations.CreateModel(
            name='TransaksiMasuk',
            fields=[
            ],
            options={
                'verbose_name': 'Transaksi Masuk',
                'proxy': True,
                'verbose_name_plural': 'Transaksi Masuk',
                'indexes': [],
            },
            bases=('kabupaten.transaksi',),
        ),
        migrations.CreateModel(
            name='TransaksiMasukSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Transaksi Masuk Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Transaksi Masuk Setwan',
                'indexes': [],
            },
            bases=('kabupaten.transaksi',),
        ),
        migrations.AddField(
            model_name='masuk',
            name='id_pihak_ketiga',
            field=models.ForeignKey(db_column=b'id_pihak_ketiga', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.PihakKetiga', verbose_name=b'Pihak Ketiga'),
        ),
        migrations.AddField(
            model_name='keluar',
            name='id_pegawai',
            field=models.ForeignKey(db_column=b'id_pegawai', on_delete=django.db.models.deletion.CASCADE, to='kabupaten.Pegawai', verbose_name=b'Pegawai'),
        ),
        migrations.CreateModel(
            name='KeluarSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Keluar Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Keluar Setwan',
                'indexes': [],
            },
            bases=('kabupaten.keluar',),
        ),
        migrations.CreateModel(
            name='MasukSetwan',
            fields=[
            ],
            options={
                'verbose_name': '01 : Masuk Setwan',
                'proxy': True,
                'verbose_name_plural': '01 : Masuk Setwan',
                'indexes': [],
            },
            bases=('kabupaten.masuk',),
        ),
    ]
