cvs add  dpupr/migrations
cvs add  dpkp/migrations
cvs add  sosial/migrations
cvs add  disnakertrans/migrations
cvs add  dpppa/migrations
cvs add  dkp/migrations
cvs add  dlh/migrations
cvs add  dpmd/migrations
cvs add  dppkb/migrations
cvs add  kominfo/migrations
cvs add  dkukmp/migrations
cvs add  dpmptsp/migrations
cvs add  dko/migrations
cvs add  perpustakaan/migrations
cvs add  kearsipan/migrations
cvs add  perikanan/migrations
cvs add  pariwisata/migrations
cvs add  perdagangan/migrations
cvs add  bkppd/migrations
cvs add  bppd/migrations

cvs add  dpupr/migrations/*.py
cvs add  dpkp/migrations/*.py
cvs add  sosial/migrations/*.py
cvs add  disnakertrans/migrations/*.py
cvs add  dpppa/migrations/*.py
cvs add  dkp/migrations/*.py
cvs add  dlh/migrations/*.py
cvs add  dpmd/migrations/*.py
cvs add  dppkb/migrations/*.py
cvs add  kominfo/migrations/*.py
cvs add  dkukmp/migrations/*.py
cvs add  dpmptsp/migrations/*.py
cvs add  dko/migrations/*.py
cvs add  perpustakaan/migrations/*.py
cvs add  kearsipan/migrations/*.py
cvs add  perikanan/migrations/*.py
cvs add  pariwisata/migrations/*.py
cvs add  perdagangan/migrations/*.py
cvs add  bkppd/migrations/*.py
cvs add  bppd/migrations/*.py
