cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Setwan/g  | sed -e s/tebingtinggi/setwan/g  | sed -e  s/38/1/g > setwan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Setda/g  | sed -e s/tebingtinggi/setda/g  | sed -e  s/38/2/g > setda/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPUPR/g  | sed -e s/tebingtinggi/dpupr/g  | sed -e  s/38/3/g > dpupr/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Dishub/g  | sed -e s/tebingtinggi/dishub/g  | sed -e  s/38/4/g > dishub/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Dinkes/g  | sed -e s/tebingtinggi/dinkes/g  | sed -e  s/38/5/g > dinkes/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Disdik/g  | sed -e s/tebingtinggi/disdik/g  | sed -e  s/38/7/g > disdik/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Perpustakaan/g  | sed -e s/tebingtinggi/perpustakaan/g  | sed -e  s/38/8/g > perpustakaan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Sosial/g  | sed -e s/tebingtinggi/sosial/g  | sed -e  s/38/9/g > sosial/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPMD/g  | sed -e s/tebingtinggi/dpmd/g  | sed -e  s/38/10/g > dpmd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPPPA/g  | sed -e s/tebingtinggi/dpppa/g  | sed -e  s/38/11/g > dpppa/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DukCatPil/g  | sed -e s/tebingtinggi/dukcatpil/g  | sed -e  s/38/12/g > dukcatpil/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Pertanian/g  | sed -e s/tebingtinggi/pertanian/g  | sed -e  s/38/13/g > pertanian/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DKP/g  | sed -e s/tebingtinggi/dkp/g  | sed -e  s/38/15/g > dkp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DKUKMP/g  | sed -e s/tebingtinggi/dkukmp/g  | sed -e  s/38/16/g > dkukmp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPMPTSP/g  | sed -e s/tebingtinggi/dpmptsp/g  | sed -e  s/38/18/g > dpmptsp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BKD/g  | sed -e s/tebingtinggi/bkd/g  | sed -e  s/38/19/g > bkd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Inspektorat/g  | sed -e s/tebingtinggi/inspektorat/g  | sed -e  s/38/20/g > inspektorat/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BAPPEDA/g  | sed -e s/tebingtinggi/bappeda/g  | sed -e  s/38/21/g > bappeda/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DLH/g  | sed -e s/tebingtinggi/dlh/g  | sed -e  s/38/22/g > dlh/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DKO/g  | sed -e s/tebingtinggi/dko/g  | sed -e  s/38/23/g > dko/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/KESBANGPOL/g  | sed -e s/tebingtinggi/kesbangpol/g  | sed -e  s/38/24/g > kesbangpol/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/SATPOLPP/g  | sed -e s/tebingtinggi/satpolpp/g  | sed -e  s/38/25/g > satpolpp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BKPPD/g  | sed -e s/tebingtinggi/bkppd/g  | sed -e  s/38/26/g > bkppd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Paringin/g  | sed -e s/tebingtinggi/paringin/g  | sed -e  s/38/28/g > paringin/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Lampihong/g  | sed -e s/tebingtinggi/lampihong/g  | sed -e  s/38/31/g > lampihong/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Batumandi/g  | sed -e s/tebingtinggi/batumandi/g  | sed -e  s/38/32/g > batumandi/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Juai/g  | sed -e s/tebingtinggi/juai/g  | sed -e  s/38/33/g > juai/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Awayan/g  | sed -e s/tebingtinggi/awayan/g  | sed -e  s/38/34/g > awayan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Halong/g  | sed -e s/tebingtinggi/halong/g  | sed -e  s/38/35/g > halong/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/ParinginSelatan/g  | sed -e s/tebingtinggi/paringinselatan/g  | sed -e  s/38/36/g > paringinselatan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPBD/g  | sed -e s/tebingtinggi/bpbd/g  | sed -e  s/38/39/g > bpbd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPKP/g  | sed -e s/tebingtinggi/dpkp/g  | sed -e  s/38/40/g > dpkp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Disnakertrans/g  | sed -e s/tebingtinggi/disnakertrans/g  | sed -e  s/38/41/g > disnakertrans/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPPKB/g  | sed -e s/tebingtinggi/dppkb/g  | sed -e  s/38/42/g > dppkb/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Kominfo/g  | sed -e s/tebingtinggi/kominfo/g  | sed -e  s/38/43/g > kominfo/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Kearsipan/g  | sed -e s/tebingtinggi/kearsipan/g  | sed -e  s/38/44/g > kearsipan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Perikanan/g  | sed -e s/tebingtinggi/perikanan/g  | sed -e  s/38/45/g > perikanan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Pariwisata/g  | sed -e s/tebingtinggi/pariwisata/g  | sed -e  s/38/46/g > pariwisata/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Perdagangan/g  | sed -e s/tebingtinggi/perdagangan/g  | sed -e  s/38/47/g > perdagangan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPPD/g  | sed -e s/tebingtinggi/bppd/g  | sed -e  s/38/48/g > bppd/admin.py
