cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Setwan/g  | sed -e s/tebingtinggi/setwan/g  | sed -e  s/38/1/g > setwan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Setda/g  | sed -e s/tebingtinggi/setda/g  | sed -e  s/38/2/g > setda/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Dispu/g  | sed -e s/tebingtinggi/dispu/g  | sed -e  s/38/3/g > dispu/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Dishub/g  | sed -e s/tebingtinggi/dishub/g  | sed -e  s/38/4/g > dishub/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Dinkes/g  | sed -e s/tebingtinggi/dinkes/g  | sed -e  s/38/5/g > dinkes/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Disdik/g  | sed -e s/tebingtinggi/disdik/g  | sed -e  s/38/7/g > disdik/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/KPDAD/g  | sed -e s/tebingtinggi/kpdad/g  | sed -e  s/38/8/g > kpdad/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/SNT/g  | sed -e s/tebingtinggi/snt/g  | sed -e  s/38/9/g > snt/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPMPD/g  | sed -e s/tebingtinggi/bpmpd/g  | sed -e  s/38/10/g > bpmpd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPPAKB/g  | sed -e s/tebingtinggi/bppakb/g  | sed -e  s/38/11/g > bppakb/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DukCatPil/g  | sed -e s/tebingtinggi/dukcatpil/g  | sed -e  s/38/12/g > dukcatpil/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Pertanian/g  | sed -e s/tebingtinggi/pertanian/g  | sed -e  s/38/13/g > pertanian/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPPKP/g  | sed -e s/tebingtinggi/bppkp/g  | sed -e  s/38/15/g > bppkp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Perindagkop/g  | sed -e s/tebingtinggi/perindagkop/g  | sed -e  s/38/16/g > perindagkop/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/KP2TPM/g  | sed -e s/tebingtinggi/kp2tpm/g  | sed -e  s/38/18/g > kp2tpm/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/DPPKAD/g  | sed -e s/tebingtinggi/dppkad/g  | sed -e  s/38/19/g > dppkad/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Inspektorat/g  | sed -e s/tebingtinggi/inspektorat/g  | sed -e  s/38/20/g > inspektorat/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BAPPEDA/g  | sed -e s/tebingtinggi/bappeda/g  | sed -e  s/38/21/g > bappeda/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BLHK/g  | sed -e s/tebingtinggi/blhk/g  | sed -e  s/38/22/g > blhk/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Disporaparbud/g  | sed -e s/tebingtinggi/disporaparbud/g  | sed -e  s/38/23/g > disporaparbud/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/KESBANGPOL/g  | sed -e s/tebingtinggi/kesbangpol/g  | sed -e  s/38/24/g > kesbangpol/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/SATPOLPP/g  | sed -e s/tebingtinggi/satpolpp/g  | sed -e  s/38/25/g > satpolpp/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BKD/g  | sed -e s/tebingtinggi/bkd/g  | sed -e  s/38/26/g > bkd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Paringin/g  | sed -e s/tebingtinggi/paringin/g  | sed -e  s/38/28/g > paringin/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Lampihong/g  | sed -e s/tebingtinggi/lampihong/g  | sed -e  s/38/31/g > lampihong/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Batumandi/g  | sed -e s/tebingtinggi/batumandi/g  | sed -e  s/38/32/g > batumandi/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Juai/g  | sed -e s/tebingtinggi/juai/g  | sed -e  s/38/33/g > juai/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Awayan/g  | sed -e s/tebingtinggi/awayan/g  | sed -e  s/38/34/g > awayan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Halong/g  | sed -e s/tebingtinggi/halong/g  | sed -e  s/38/35/g > halong/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/ParinginSelatan/g  | sed -e s/tebingtinggi/paringinselatan/g  | sed -e  s/38/36/g > paringinselatan/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/BPBD/g  | sed -e s/tebingtinggi/bpbd/g  | sed -e  s/38/39/g > bpbd/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B40/g  | sed -e s/tebingtinggi/b40/g  | sed -e  s/38/40/g > b40/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B41/g  | sed -e s/tebingtinggi/b41/g  | sed -e  s/38/41/g > b41/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B42/g  | sed -e s/tebingtinggi/b42/g  | sed -e  s/38/42/g > b42/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B43/g  | sed -e s/tebingtinggi/b43/g  | sed -e  s/38/43/g > b43/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B44/g  | sed -e s/tebingtinggi/b44/g  | sed -e  s/38/44/g > b44/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B45/g  | sed -e s/tebingtinggi/b45/g  | sed -e  s/38/45/g > b45/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B46/g  | sed -e s/tebingtinggi/b46/g  | sed -e  s/38/46/g > b46/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B47/g  | sed -e s/tebingtinggi/b47/g  | sed -e  s/38/47/g > b47/admin.py
cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/B48/g  | sed -e s/tebingtinggi/b48/g  | sed -e  s/38/48/g > b48/admin.py
