python manage.py startapp dpupr
python manage.py startapp dpkp
python manage.py startapp sosial
python manage.py startapp disnakertrans
python manage.py startapp dpppa
python manage.py startapp dkp
python manage.py startapp dlh
python manage.py startapp dpmd
python manage.py startapp dppkb
python manage.py startapp kominfo
python manage.py startapp dkukmp
python manage.py startapp dpmptsp
python manage.py startapp dko
python manage.py startapp perpustakaan
python manage.py startapp kearsipan
python manage.py startapp perikanan
python manage.py startapp pariwisata
python manage.py startapp perdagangan
python manage.py startapp bkppd
python manage.py startapp bppd
