cat persediaan_barang5_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > persediaan_barang5_setda.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > persediaan_barang5_dispu.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > persediaan_barang5_dishub.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > persediaan_barang5_dinkes.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > persediaan_barang5_disdik.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > persediaan_barang5_kpdad.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > persediaan_barang5_snt.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > persediaan_barang5_bpmpd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > persediaan_barang5_bppakb.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > persediaan_barang5_dukcatpil.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > persediaan_barang5_pertanian.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > persediaan_barang5_bppkp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > persediaan_barang5_perindagkop.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > persediaan_barang5_kp2tpm.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > persediaan_barang5_dppkad.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > persediaan_barang5_inspektorat.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > persediaan_barang5_bappeda.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > persediaan_barang5_blhk.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > persediaan_barang5_disporaparbud.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > persediaan_barang5_kesbangpol.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > persediaan_barang5_satpolpp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > persediaan_barang5_bkd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > persediaan_barang5_paringin.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > persediaan_barang5_lampihong.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > persediaan_barang5_batumandi.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > persediaan_barang5_juai.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > persediaan_barang5_awayan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > persediaan_barang5_halong.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > persediaan_barang5_paringinselatan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > persediaan_barang5_tebingtinggi.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > persediaan_barang5_bpbd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > persediaan_barang5_b40.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > persediaan_barang5_b41.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > persediaan_barang5_b42.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > persediaan_barang5_b43.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > persediaan_barang5_b44.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > persediaan_barang5_b45.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > persediaan_barang5_b46.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > persediaan_barang5_b47.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > persediaan_barang5_b48.sql
cat persediaan_barang5_*.sql > ../gabungan_persediaan_barang5.sql
