cat buku_penerimaan_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > buku_penerimaan_setda.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > buku_penerimaan_dpupr.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > buku_penerimaan_dishub.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > buku_penerimaan_dinkes.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > buku_penerimaan_disdik.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > buku_penerimaan_perpustakaan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > buku_penerimaan_sosial.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > buku_penerimaan_dpmd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > buku_penerimaan_dpppa.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > buku_penerimaan_dukcatpil.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > buku_penerimaan_pertanian.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > buku_penerimaan_dkp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > buku_penerimaan_dkukmp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > buku_penerimaan_dpmptsp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > buku_penerimaan_bkd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > buku_penerimaan_inspektorat.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > buku_penerimaan_bappeda.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > buku_penerimaan_dlh.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > buku_penerimaan_dko.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > buku_penerimaan_kesbangpol.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > buku_penerimaan_satpolpp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > buku_penerimaan_bkppd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > buku_penerimaan_paringin.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > buku_penerimaan_lampihong.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > buku_penerimaan_batumandi.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > buku_penerimaan_juai.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > buku_penerimaan_awayan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > buku_penerimaan_halong.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > buku_penerimaan_paringinselatan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > buku_penerimaan_tebingtinggi.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > buku_penerimaan_bpbd.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > buku_penerimaan_dpkp.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > buku_penerimaan_disnakertrans.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > buku_penerimaan_dppkb.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > buku_penerimaan_kominfo.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > buku_penerimaan_kearsipan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > buku_penerimaan_perikanan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > buku_penerimaan_pariwisata.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > buku_penerimaan_perdagangan.sql
cat buku_penerimaan_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > buku_penerimaan_bppd.sql
cat buku_penerimaan_*.sql > ../gabungan_buku_penerimaan.sql
