cat persediaan_barang5_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > persediaan_barang5_setda.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > persediaan_barang5_dpupr.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > persediaan_barang5_dishub.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > persediaan_barang5_dinkes.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > persediaan_barang5_disdik.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > persediaan_barang5_perpustakaan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > persediaan_barang5_sosial.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > persediaan_barang5_dpmd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > persediaan_barang5_dpppa.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > persediaan_barang5_dukcatpil.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > persediaan_barang5_pertanian.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > persediaan_barang5_dkp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > persediaan_barang5_dkukmp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > persediaan_barang5_dpmptsp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > persediaan_barang5_bkd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > persediaan_barang5_inspektorat.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > persediaan_barang5_bappeda.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > persediaan_barang5_dlh.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > persediaan_barang5_dko.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > persediaan_barang5_kesbangpol.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > persediaan_barang5_satpolpp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > persediaan_barang5_bkppd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > persediaan_barang5_paringin.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > persediaan_barang5_lampihong.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > persediaan_barang5_batumandi.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > persediaan_barang5_juai.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > persediaan_barang5_awayan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > persediaan_barang5_halong.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > persediaan_barang5_paringinselatan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > persediaan_barang5_tebingtinggi.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > persediaan_barang5_bpbd.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > persediaan_barang5_dpkp.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > persediaan_barang5_disnakertrans.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > persediaan_barang5_dppkb.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > persediaan_barang5_kominfo.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > persediaan_barang5_kearsipan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > persediaan_barang5_perikanan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > persediaan_barang5_pariwisata.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > persediaan_barang5_perdagangan.sql
cat persediaan_barang5_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > persediaan_barang5_bppd.sql
cat persediaan_barang5_*.sql >> ../gabungan_persediaan_rekap_kabupaten.sql
